# Generated by Django 4.2.6 on 2023-10-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_palindrome',
            field=models.BooleanField(default=False),
        ),
    ]
